### ISSUE TITLE
Couldn't load plugin 'QWater' 

### ISSUE THREAD

**Issue by VoldemarNo** [jorgealmerio/QWater#19]
SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/nogaj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\__init__.py", line 28, in 
    from .QWaterPlugin import QWaterPlugin
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/nogaj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 52, in 
    from .QWater_03Export import *
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/nogaj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWater_03Export.py", line 39, in 
    from .addon.waterNet.QWaterNet import QWaterNet_addon
  File "C:\PROGRA~1/QGIS33~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/nogaj/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\addon\waterNet\QWaterNet.py", line 205
    match connCount:
          ^
SyntaxError: invalid syntax

Python version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS version: 3.34.5-Prizren Prizren, 4b308492

**Comment by jorgealmerio** [comment]
Fixed in QWater 3.3.1, please update.
Retrocompatibility with python<3.10 (match function)

Let me know if it fixed.

**Comment by VoldemarNo** [comment]
Yes, it fixed now. Thank you very much!

**Comment by VoldemarNo** [comment]
Thank you very much for you quick  response. Could you please send me previous version Qwater for secure oneself “de bene esse”?

**Comment by jorgealmerio** [comment]
You can get all versions here:
[https://plugins.qgis.org/plugins/QWater/#plugin-versions]

**Comment by VoldemarNo** [comment]
Ok.
