### ISSUE TITLE
Couldn't load plugin 'QWater'

### ISSUE THREAD

**Issue by DanielKimmich** [jorgealmerio/QWater#21]
Dear developer of the plugin

I have problems installing "QWater" the plugin when the library version is "numpy 2.0.1"

The incompatibility happens because for another plugin it asks me to install the "panda" library and this updates the version of the "numpy 2.0.1"

Versión de QGIS | 3.38.1-Grenoble
Versión de Python | 3.10.12
Versión del SO | Pop!_OS 22.04 LTS
QWater | 3.3.1

If the installation works for me when the library version is "numpy 1.21.5".

Thank you so much
D.K.

**Comment by DanielKimmich** [comment]
Another error I have is when I have a base map for example "osm standard" and I open the "settings" option I get the following:

2024-08-07T18:38:53     WARNING    Error de Python : Ha ocurrido un error mientras se ejecutaba el código de Python: Vea el registro de mensajes (Error de Python) para más detalles.

2024-08-07T18:38:53     WARNING    Traceback (most recent call last):
              File "/home/danielkimmich/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QWater/QWaterPlugin.py", line 621, in showSettings
              self.DEM_ComboBox_prepare(widget)
              File "/home/danielkimmich/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QWater/QWaterPlugin.py", line 1140, in DEM_ComboBox_prepare
              if cap             TypeError: '

**Comment by jorgealmerio** [comment]
File "/home/danielkimmich/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QWater/QWaterPlugin.py", line 1140, in DEM_ComboBox_prepare
if cap TypeError: '

Yes, You are right! I got this error too here!
I will try to fix it as soon as possible!
Thank you!

**Comment by DanielKimmich** [comment]
Thank you very much for taking care of the issue

I would like to tell you that to solve the problem with the "panda" library, I installed an older version (pip install pandas==1.5.2) so that the "numpy 1.21.5" library does not change.

The plugin that I have been integrating with qgis is "Smart_Map" + this "qwater"

Regards

**Comment by jorgealmerio** [comment]
Could you please open a different issue, Because these are 2 different issues.
Thank you!

**Comment by DanielKimmich** [comment]
I created a new case due to a DEM error

[https://github.com/jorgealmerio/QWater/issues/22](url)

Regards

**Comment by LeonardoRuan** [comment]
Hello Daniel, how are you? My name is Leonardo, and I am a graduate student here in Brazil. I was trying to use the QWater plugin in QGIS, but I encountered a Python error. I saw on GitHub that you managed to fix this error. Could you please explain how you did it?

> Criei um novo caso devido a um erro DEM
> 
> [https://github.com/jorgealmerio/QWater/issues/22](url)
> 
> Cumprimentos



> Muito obrigado por cuidar do problema
> 
> Gostaria de informar que para resolver o problema com a biblioteca "panda", instalei uma versão mais antiga (pip install pandas==1.5.2) para que a biblioteca "numpy 1.21.5" não mude.
> 
> O plugin que venho integrando com o qgis é o "Smart_Map" + este "qwater"
> 
> Cumprimentos
