### ISSUE TITLE
Error when I have a base map

### ISSUE THREAD

**Issue by DanielKimmich** [jorgealmerio/QWater#22]
Dear developer of the plugin

I have error when I have a base map for example "osm standard" and I open the "settings" option I get the following:

2024-08-07T18:38:53 WARNING Error de Python : Ha ocurrido un error mientras se ejecutaba el código de Python: Vea el registro de mensajes (Error de Python) para más detalles.

2024-08-07T18:38:53 WARNING Traceback (most recent call last):
File "/home/danielkimmich/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QWater/QWaterPlugin.py", line 621, in showSettings
self.DEM_ComboBox_prepare(widget)
File "/home/danielkimmich/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QWater/QWaterPlugin.py", line 1140, in DEM_ComboBox_prepare
if cap TypeError: '

Versión de QGIS | 3.38.1-Grenoble
Versión de Python | 3.10.12
Versión del SO | Pop!_OS 22.04 LTS
QWater | 3.3.1

Thank you so much
D.K.

**Comment by jorgealmerio** [comment]
Fixed on version 3.3.2.
Please, give me a feedback.

**Comment by DanielKimmich** [comment]
Dear, I downloaded the corrected version and I no longer had the error.

Thank you very much
