### ISSUE TITLE
Error when try to do the relation of the created shapes

### ISSUE THREAD

**Issue by LeandroCPinto** [jorgealmerio/QWater#23]
Dear developer of plugin

Thank you for this plugin, I try to use the plugin, but I am facing some problems to do the relation between created shapes and EPANET informations. Follow the error occourred: 

 File "C:\Users/Docker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 633, in showSettings
              self.DEM_ComboBox_prepare(widget)
              File "C:\Users/Docker/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 1141, in DEM_ComboBox_prepare
              if not (caps & Qgis.RasterInterfaceCapability.IdentifyValue): #era: caps              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: type object 'Qgis' has no attribute 'RasterInterfaceCapability'

Can you give some help with it?

Thanks and regards.

**Comment by jorgealmerio** [comment]
This error was solved in QWater version 3.3.2.
Let me know what version you are using.
Could you give me more details how to reproduce the error?

If this error occured after you are updated panda version to >= 2.0, please see #21. 
It can be solved by installing a older version (pip install pandas==1.5.2)

**Comment by LeandroCPinto** [comment]
Dear jorgealmerio, thank you for the answer!

I installed an older Qwater version 3.1.9 (https://plugins.qgis.org/plugins/QWater/#plugin-versions) and it solves the issue.

Thank you.

**Comment by ckarren** [comment]
I get the same error trace when trying to use GEOtiff files for the DEM. 
 WARNING    Traceback (most recent call last):
              File "C:\Users/xxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 633, in showSettings
              self.DEM_ComboBox_prepare(widget)
              File "C:\Users/xxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 1141, in DEM_ComboBox_prepare
              if not (caps & Qgis.RasterInterfaceCapability.IdentifyValue): #era: caps              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             AttributeError: type object 'Qgis' has no attribute 'RasterInterfaceCapability'

If any of my layers are .tif I get this error. I cannot assign a DEM layer, and therefore cannot get elevation. 

I'm using QGIS 3.34.14, Pandas 2.2.3, QWater 3.3.2, Python 3.12.8, Windows 11 OS

**Comment by jorgealmerio** [comment]
Please, Update Qgis to version 3.40.+.
