### ISSUE TITLE
Erro RasterInterfaceCapability

### ISSUE THREAD

**Issue by Dougbr1992** [jorgealmerio/QWater#25]
Jorge, que está mensagem o encontre bem!

primeiramente, obrigado pelo desenvolvimento desse valioso plugin.

Venho enfrentando problema com a versão [3.3.2], quando vou utilizar o plugin em um arquivo que contenha um raster surge o seguinte erro:

> 2024-12-03T16:01:02     WARNING    Traceback (most recent call last):
>               File "C:\Users/amarald/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 633, in showSettings
>               self.DEM_ComboBox_prepare(widget)
>               File "C:\Users/amarald/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\QWaterPlugin.py", line 1141, in DEM_ComboBox_prepare
>               if not (caps & Qgis.RasterInterfaceCapability.IdentifyValue): #era: caps              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>              AttributeError: type object 'Qgis' has no attribute 'RasterInterfaceCapability'

A versão anterior não ocorre o erro.

**Comment by jorgealmerio** [comment]
Could you please pass to me this specific raster? Or describe the steps to reproduce this error?
I could not reproduce this error on Windows.

**Comment by Dougbr1992** [comment]
Jorge, 

O erro ocorre quando clico em configurações, se eu não tenho nenhum raster no arquivo funciona normalmente, mas se eu coloco um raster ele da o erro. Pode ser um arquivo novo ou já configurado no QWATER.

E pode ser qualquer raster, inclusive as imagens do google do QuickMapServices.

![Captura de tela 2025-01-06 163958](https://github.com/user-attachments/assets/07e1ba4d-3dd5-4b65-9a83-5f1c16d966a4)

**Comment by jorgealmerio** [comment]
Bom dia!

Eu fiz vários testes aqui com a mesma versão do QWater que você indicou (3.3.2), coloquei diversos Rasters, inclusive do Quickmap service, mas nenhum deu erro. 

Eu percebi que eu estou rodando:
Qgis versão 3.40.1
Python versão 3.12.7

E você está com versões anteriores. Se você puder atualizar seu Qgis pra testar, seria interessante.
Antes disso você pode experimentar usar um perfil limpo no Qgis também. Configuração/Perfis de Usuario/Novo Perfil.

**Comment by Wiras77** [comment]
Boa Tarde!

Prezados,

Estou enfrentando o mesmo problema que o [Dougbr1992], com relação às camadas raster.
Qgis versão: 3.34.13 LTR
Python versão: 3.12.7

![erro-qgis-dem-raster](https://github.com/user-attachments/assets/c5527020-42a8-496b-b5e3-0405d3447e01)

**Comment by Dougbr1992** [comment]
Baixei e testei com a nova versão do Qgis (versão 3.40.2) e funcionou, não tive o problema com o raster.
