### ISSUE TITLE
key error b'809'

### ISSUE THREAD

**Issue by dinu-9** [jorgealmerio/QWater#26]
I ran the model after giving all the inputs, In the report section it is showing only negative pressure error but after that its showing key error '809' this type of error and the pipes are disappearing after cliking ok in report window

like this

KeyError: b'809' 
Traceback (most recent call last):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\GHydraulicsResultDialog.py", line 40, in accepted
    self.setStep(self.ui.comboStep.currentIndex())
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\GHydraulicsModelRunner.py", line 139, in setStep
    self.setStepResults(step, EpanetModel.COORDINATE_SECTIONS, GHydraulicsModel.NODE_RESULTS, self.e.getNodeResult)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\GHydraulicsModelRunner.py", line 130, in setStepResults
    results = getter(step, feature.attributes()[ididx])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QWater\EpanetResultReader.py", line 53, in getNodeResult
    offset = self.nodes[id.encode()] + step * (4 * self.nodecount + 8 * self.linkcount)
             ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: b'809'


![qwater error](https://github.com/user-attachments/assets/d0c51788-82b4-4884-94ec-a2b71f8f8428)

**Comment by jorgealmerio** [comment]
It seems to be a node ID not present.
Try to Run Make model. Second button from left of QWater Toolbar.
See the messages and try to solve.
Then Run Model again

**Comment by dinu-9** [comment]
Thank you so much sir for replying, you were right also there were null geometries present in the junction layers after deleting that it ran correctly, thank you again sir , also sir does this plugin have any limitations over number of junction and pipe

**Comment by jorgealmerio** [comment]
you're welcome!
There is no known limitations!
